# -*- coding: utf-8 -*-
"""MyPractises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLMls8LoWtfprt4YdyYPos2DhKVP55TF

دستورات ورودی و خروجی
"""

#محاسبه مساحت متوازی الاضلاع
base = float(input("length of base: "))
height = float(input("height: "))
area = base * height
print("area is ", area)

#محاسبه حجم و مساحت استوانه
pi = 22/7
radius = float(input("Radius of cylinder: "))
height = float(input("height of cylinder: "))
volume = pi * (radius**2) * height
surarea = (2*pi*radius*height) + (2*(pi*radius**2))
print("volume is: ", volume)
print ("surface area is: ", surarea)

#ایجاد اعداد مختلط و نمایش آن
a = int(input(" Enter real part: "))
b = int(input("Enter image part: "))
complex1 = complex(a, b)
print(complex1)

#خواندن یگ رشته و تعداد تکرار آن
s = input("Enter a string: ")
rep = int(input("Enter repeat: "))
print(s*rep)

#نمایش تاریخ و زمان فعلی
import datetime
now = datetime.datetime.now()
print("current date and time: ", now.strftime("%Y-%m-%d %H: %M: %S"))

#تعیین پوسته اجرا
import struct
print(struct.calcsize("P")*8)

#نمایش اطلاعات پلتفرم
import platform
import os
print("name is: ", os.name)
print("platform system is: ", platform.system())
print("platform release is: ", platform.release())

#نمایش نام سایت بسته های پایتون
import site
print("Site package is ", site.getsitepackages())

#اجرای یک برنامه اجرایی خارجی در پایتون(ماشین حساب)
from subprocess import call
call([".exe"])

#خواندن نام و مسیر فایل فعلی در حال اجرا
import os
print("current file name is: ", os.path.realpath(__file__))

#نمایش تعداد پردازنده های رایانه
import multiprocessing
print("count cpu is: ", multiprocessing.cpu_count())

#نمایش نام کاربر فعلی
import getpass
print("username is : ", getpass.getuser())

#خواندن سه عدد و مرتب کردن آن
x = int(input(" num 1 : "))
y = int(input(" num 2 : "))
z= int(input(" num 3 : "))
a1 = min(x, y, z)
a3 = max(x, y, z)
a2 = (x + y + z)-a1-a3
print("number in sorted order: ", a1 , a2 , a3)

#نمایش نام میزبان در حال اجرا
import socket
host_name = socket .gethostname()
print ("host name : ", host_name)

#نمایش اطلاعات محیط کاربران
import os
print(os.environ)

"""ساختار تصمیم و حلقه تکرار"""

#گرفتن شماره دانشجویی  و معدل ان دانشجو و نشان دادن معدل دوم
id1=-1
id2=-1
max1=-1
max2=-1
n = int(input("enter number of students: "))
if n<2:
    print('please enter a number greater than one')
else:
    for i in range(1, n+1):
      id = int(input("enter id: "))
      average = float(input("enter average: "))
      if average > max1:
        id2=id1
        max2=max1
        max1=average
        id1=id
      else:
        if average>max2:
          max2=average
          id2=id
    print("max2 = ", max2, '\t', "id2 = ", id2)

#خواندن اعداد از وزودی و تشخیص کامل است یا نه
while True: #ایجاد یک حلقه بی نهایت
  num = int(input("enter a number: "))
  sum = 0
  for i in range(1, num): #ایجاد یک حلقه و شمارش 1 تا num-1
    if (num % i == 0): #اگر num بر i بخشپذیر باشد
      sum += i
  if (sum == num):
    print('\t', "perfected")
  else:
    print('\t', "Not perfected")
  yes = input("continue? ")
  if (yes [0]== 'N' or yes[0]=='n'):
    break
  else:
    continue

#تولید ان جمله از سری فیبوناتچی
#سری فیبوناچی= 1 1 2 3 5 8 13و ...
f1=1
f2=1
n=int(input("Enter a number: "))
if n == 1:
  print(f1)
  exit(0)
elif n==2:
  print(f1)
  print(f2)
else:
  print(f1)
  print(f2)
  i = 3
  while i <= n:
    f3 = f1 + f2
    print(f3, " ")
    f1=f2
    f2=f3
    i = i + 1

#پیمایش رشته با for
s= input ("enter a string: ")
for i in s:
  print(i, end= ' ')

#محاسبه بهره وام
while True:
  m = int(input("loan amount: ")) #مقدار وام
  n = int(input("number of installment: ")) #تعداد اقساط
  s = int(input("interst rate: ")) #نرخ بهره
  l = m*(n+1)*s/2400 #بهره وام
  t = l + m #کل وام پرداختی
  p = t/n #پرداختی هر قسط
  print("total loan paid = ", t, '\t', p)
  ansi = input("Do you want to continue?")#شرط ادامه
  if ansi[0] == 'n':
    break

#خواندن سه مقدار از ورودی و آنها را به ترتیب صعودی چاپ کند